theme = "soho"
baseurl = "https://kothiba.github.io/tarutaru-life/"
languageCode = "ja"
#title = "TARUTARU-LIFE"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
summarylength = 5
enableEmoji = true
paginate = 5
disqusShortname = "https-kothiba-github-io"
googleAnalytics = "UA-190729144-1"

[params]
title = "TARUTARU-LIFE"
description = "TARUTARU-LIFE"
# gravatar = "soho@example.com"
images = ["images/profile.png"]
profilePicture = "images/taichi-aikon.jpg"
copyright = "TARUTARU"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["posts"]
amazonJpAffiliate = "baumkuchen0f-22"

## Set custom theme color.
# themeColor = "#fc2803"

  #[[params.socialIcons]]
  #icon = "fa-linkedin"
  #title = "Linkedin"
  #url = "#"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/kothiba"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/kothiba"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "Work"
  identifier = "work"
  weight = 20
  url = "/work/"

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  #[[menu.main]]
  #name = "Tags"
  #weight = 200
  #identifier = "tags"
  #url = "/tags/"


[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true